sudo: false
language: ruby
bundler_args: --without development
cache: bundler

rvm: 2.4.1

env:
 - INSTANCE=ubuntu-14-04
 - INSTANCE=ubuntu-16-04
 - INSTANCE=centos-6
 - INSTANCE=centos-7
 - INSTANCE=debian-7
 - INSTANCE=debian-8
 - INSTANCE=fedora-26
 - INSTANCE=fedora-27

matrix:
  allow_failures: # allow failues of integration tests as the forks might miss the DO token
  - env: INSTANCE=ubuntu-14-04
  - env: INSTANCE=ubuntu-16-04
  - env: INSTANCE=centos-6
  - env: INSTANCE=centos-7
  - env: INSTANCE=debian-7
  - env: INSTANCE=debian-8
  - env: INSTANCE=fedora-26
  - env: INSTANCE=fedora-27

script:
  -  bundle exec rake prepare_do_env kitchen KITCHEN_LOCAL_YAML=.kitchen.do.yml
